service: slack-to-jira

custom:
  defaultStage: dev
  api_version: v0

provider:
  name: aws
  runtime: provided
  region: ap-northeast-1
  environment:
    ${file(./env.yml)}

functions:
  subscribe:
    handler: subscribe
    events:
      - http:
          path: subscribe
          method: post