name: dart-sls

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest

    steps:

    - name: checkout
      uses: actions/checkout@v1

    - name: pub get
      run: pub get

    - name: build
      run: dart2native ./src/main.dart -o ./bootstrap

    - name: install aws
      run: apt-get -y update && apt-get -y install awscli

    - name: configure aws
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: get env
      run: |
        aws s3 cp s3://limit7412-workflow-env/slack_to_jira/dev/env.yml .

    - name: deploy
      uses: serverless/github-action@master
      with:
        args: deploy -s dev > /dev/null 2>&1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
